<a href="https://colab.research.google.com/github/nananana25/MSC151/blob/main/Week_2_house_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('/content/sample_data/BostonHousing.csv')
display(df.head())

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

from matplotlib import pyplot as plt
_df_0['crim'].plot(kind='hist', bins=20, title='crim')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['zn'].plot(kind='hist', bins=20, title='zn')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['indus'].plot(kind='hist', bins=20, title='indus')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['nox'].plot(kind='hist', bins=20, title='nox')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='crim', y='zn', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='zn', y='indus', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='indus', y='nox', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='nox', y='rm', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['chas']
  ys = series['crim']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('chas', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('chas')
_ = plt.ylabel('crim')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['chas']
  ys = series['zn']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('chas', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('chas')
_ = plt.ylabel('zn')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['chas']
  ys = series['indus']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('chas', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('chas')
_ = plt.ylabel('indus')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['chas']
  ys = series['nox']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('chas', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('chas')
_ = plt.ylabel('nox')

from matplotlib import pyplot as plt
_df_12['crim'].plot(kind='line', figsize=(8, 4), title='crim')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['zn'].plot(kind='line', figsize=(8, 4), title='zn')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['indus'].plot(kind='line', figsize=(8, 4), title='indus')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['nox'].plot(kind='line', figsize=(8, 4), title='nox')
plt.gca().spines[['top', 'right']].set_visible(False)

# Task
Analyze the feature importance of 'crim', 'age', and 'dis' in predicting 'medv' using a Random Forest Regressor with an 80/20 train-test split on the dataset from "/content/sample_data/BostonHousing.csv".

## Select features and target

### Subtask:
Define the features (X) and the target variable (y) based on the user's request.


**Reasoning**:
Define the features and the target variable based on the user's request.



In [2]:
features = ['crim', 'age', 'dis']
X = df[features]
y = df['medv']

## Split data

### Subtask:
Split the data into training and testing sets using an 80/20 ratio.


**Reasoning**:
Split the data into training and testing sets using an 80/20 ratio and a random state for reproducibility.



In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

display(X_train.head())
display(X_test.head())
display(y_train.head())
display(y_test.head())

crim   age     dis
477  15.02340  97.3  2.1007
15    0.62739  56.5  4.4986
332   0.03466  23.3  6.6407
423   7.05042  85.1  2.0218
19    0.72580  69.5  3.7965

crim   age     dis
173  0.09178  84.1  2.6463
274  0.05644  32.9  4.0776
491  0.10574  98.8  1.8681
72   0.09164   7.8  5.2873
452  5.09017  91.8  2.3682

477    12.0
15     19.9
332    19.4
423    13.4
19     18.2
Name: medv, dtype: float64

173    23.6
274    32.4
491    13.6
72     22.8
452    16.1
Name: medv, dtype: float64

## Train random forest

### Subtask:
Train a Random Forest Regressor model on the training data.


**Reasoning**:
Import RandomForestRegressor and train the model on the training data.



In [4]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

## Calculate feature importance

### Subtask:
Calculate and display the feature importance scores from the trained model.


**Reasoning**:
Calculate and display the feature importance scores from the trained model.



In [6]:
import pandas as pd

feature_importances = pd.Series(model.feature_importances_, index=X.columns)
print("Feature Importance Scores:")
print(feature_importances)

Feature Importance Scores:
crim    0.521527
age     0.184708
dis     0.293764
dtype: float64


## Summary:

### Data Analysis Key Findings

*   The features selected for the analysis were 'crim', 'age', and 'dis', with 'medv' as the target variable.
*   The dataset was split into training and testing sets with an 80/20 ratio.
*   A Random Forest Regressor model was trained on the training data.
*   The feature importance scores calculated from the trained model are: 'crim': 0.521527, 'age': 0.184708, and 'dis': 0.293764.

### Insights or Next Steps

*   'crim' is the most important feature among the selected ones for predicting 'medv', followed by 'dis' and then 'age'.
*   Further analysis could involve including more features to see how their importance compares to the current set or evaluating the model's performance using the test set.
